
# This jupyter notebook is done as a refresher on applying logistic regression along with using pandas' get dummies methods for one hot encoding.

# The dataset used is from kaggle.com. The heart disease UCI dataset seemed like a reasonably clean dataset to work with to refresh knowledge on using classifiers and to apply other analytics or methods from data science.

In [9]:

import numpy as np

import pandas as pd

heart_dataframe = pd.read_csv(r"C:\Users\KennoHead\Desktop\Data Science and Machine Learning Refresher\heart.csv")

In [10]:

heart_dataframe.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [11]:

# original;y taught in class, but made a different dataframe to compare results
# to the original data with these one hot encoded data
heart_dataframe_trans = pd.get_dummies(heart_dataframe, columns = [ 'cp', 'thal'])

heart_dataframe_trans.head()

,age,sex,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,target,cp_0,cp_1,cp_2,cp_3,thal_0,thal_1,thal_2,thal_3
0,63,1,145,233,1,0,150,0,2.3,0,0,1,0,0,0,1,0,1,0,0
1,37,1,130,250,0,1,187,0,3.5,0,0,1,0,0,1,0,0,0,1,0
2,41,0,130,204,0,0,172,0,1.4,2,0,1,0,1,0,0,0,0,1,0
3,56,1,120,236,0,1,178,0,0.8,2,0,1,0,1,0,0,0,0,1,0
4,57,0,120,354,0,1,163,1,0.6,2,0,1,1,0,0,0,0,0,1,0

In [13]:

# train test splits and logistic model training using the original data

heart_dataframe_features_columns = list (heart_dataframe.columns)

heart_dataframe_features_columns.remove('target')

heart_dataframe_features = heart_dataframe[heart_dataframe_features_columns]

heart_dataframe_labels = heart_dataframe['target']

from sklearn.model_selection import train_test_split

X_training, X_testing, Y_training, Y_testing = train_test_split(heart_dataframe_features, heart_dataframe_labels, test_size = .3, random_state = 0)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_reg_clssr = LogisticRegression(max_iter=1500)

log_reg_clssr.fit(X_training, Y_training)

log_reg_predict = log_reg_clssr.predict(X_testing)

log_reg_acc = accuracy_score(Y_testing, log_reg_predict)

In [14]:

# with the original data, our model has 81.31% accuracy.
print(log_reg_acc)

0.8131868131868132

In [15]:

# train test splits with the data that has the columns "chest pain" and "thal" one hot encoded.

heart_dataframe_trans_features_columns = list (heart_dataframe_trans.columns)
heart_dataframe_trans_features_columns.remove('target')
heart_dataframe_trans_features = heart_dataframe_trans[heart_dataframe_trans_features_columns]
heart_dataframe_trans_labels = heart_dataframe_trans['target']

Xtrans_training, Xtrans_testing, Ytrans_training, Ytrans_testing = train_test_split(heart_dataframe_trans_features, heart_dataframe_trans_labels, test_size = .3, random_state = 0)

log_reg_clssr2 = LogisticRegression(max_iter=1500)
log_reg_clssr2.fit(Xtrans_training, Ytrans_training)
log_reg_predict2 = log_reg_clssr2.predict(Xtrans_testing)
log_reg_acc2 = accuracy_score(Ytrans_testing, log_reg_predict2)

In [16]:

# just simply one hot encoding two columns with multiple values seem to have improved
# the accuracy of the logistic regression model. accuracy of 84.61%

print(log_reg_acc2)

0.8461538461538461

In [21]:

# another analysis with one hot encoding
# this time encoding the columns with small integer values.

heart_dataframe_ohe = pd.get_dummies(heart_dataframe, columns = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal'])

heart_dataframe_ohe_features_columns = list(heart_dataframe_ohe)

heart_dataframe_ohe_features_columns.remove('target')

heart_dataframe_ohe_features = heart_dataframe_ohe[heart_dataframe_ohe_features_columns]

heart_dataframe_ohe_labels = heart_dataframe_ohe['target']

X3_training, X3_testing, Y3_training, Y3_testing = train_test_split(heart_dataframe_ohe_features, heart_dataframe_ohe_labels, test_size = .3, random_state = 0)

log_reg_clssr3 = LogisticRegression(max_iter=1500)
log_reg_clssr3.fit(X3_training, Y3_training)
log_reg_predict3 = log_reg_clssr3.predict(X3_testing)
log_reg_acc3 = accuracy_score(Y3_testing, log_reg_predict3)

In [22]:

# this would show that encoding the other aboved mentioned columns did not effect the accuracy score
# note that accuracy is just a metric to measure the logistic regression model's performance.
print(log_reg_acc3)

0.8461538461538461